apiVersion: v1
kind: Pod
metadata:
  name: insecure-app
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  volumes:
    - name: host-root
      hostPath:
        path: /
  containers:
    - name: app
      image: nginx:latest
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
